import Link from "next/link";
import { requireActiveCompany } from "@/lib/auth/authz";
import { prisma } from "@/lib/prisma";

export default async function DashboardPage() {
  const { company, role } = await requireActiveCompany();

  const recent = await prisma.bolRecord.findMany({
    where: { companyId: company.id },
    orderBy: { generatedAt: "desc" },
    take: 8,
    include: { generatedByUser: { select: { name: true } } },
  });

  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-2xl font-semibold text-slate-900">{company.name}</h1>
        <p className="mt-1 text-sm text-slate-500">
          {recent.length > 0
            ? `Last BOL: ${recent[0].bolNumber}`
            : "No BOLs generated yet."}
        </p>
      </div>

      {role === "VIEWER" ? (
        <p className="text-sm text-slate-500">
          Your role is Viewer — you can browse history but not generate BOLs.
        </p>
      ) : (
        <Link href="/generate" className="btn-primary w-fit">
          Generate BOL
        </Link>
      )}

      <div>
        <div className="mb-3 flex items-center justify-between">
          <h2 className="text-sm font-semibold text-slate-900">Recently generated</h2>
          <Link href="/history" className="text-sm text-slate-500 underline">
            View full history
          </Link>
        </div>

        {recent.length === 0 ? (
          <p className="text-sm text-slate-400">Nothing here yet.</p>
        ) : (
          <div className="overflow-hidden rounded-lg border border-slate-200 bg-white">
            <table className="w-full text-sm">
              <thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-4 py-2">BOL No.</th>
                  <th className="px-4 py-2">Date</th>
                  <th className="px-4 py-2">Generated By</th>
                  <th className="px-4 py-2">Status</th>
                  <th className="px-4 py-2">PDF</th>
                </tr>
              </thead>
              <tbody>
                {recent.map((r) => (
                  <tr key={r.id} className="border-t border-slate-100">
                    <td className="px-4 py-2 font-medium text-slate-900">{r.bolNumber}</td>
                    <td className="px-4 py-2 text-slate-500">
                      {r.generatedAt.toLocaleString()}
                    </td>
                    <td className="px-4 py-2 text-slate-500">{r.generatedByUser.name}</td>
                    <td className="px-4 py-2">
                      <StatusBadge status={r.status} />
                    </td>
                    <td className="px-4 py-2">
                      {r.pdfStatus === "READY" ? (
                        <a
                          href={`/api/companies/${company.id}/bols/${r.id}/pdf`}
                          target="_blank"
                          rel="noreferrer"
                          className="text-slate-700 underline"
                        >
                          Download
                        </a>
                      ) : (
                        <span className="text-xs text-slate-400">{r.pdfStatus}</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const isVoided = status === "VOIDED";
  return (
    <span
      className={`rounded-full px-2 py-0.5 text-xs font-medium ${
        isVoided ? "bg-red-100 text-red-700" : "bg-emerald-100 text-emerald-700"
      }`}
    >
      {isVoided ? "Voided" : "Active"}
    </span>
  );
}
