import { requireActiveCompany } from "@/lib/auth/authz";
import { prisma } from "@/lib/prisma";
import { VoidButton } from "@/components/VoidButton";

const PAGE_SIZE = 25;

export default async function HistoryPage({
  searchParams,
}: {
  searchParams: Promise<{ q?: string; page?: string }>;
}) {
  const { company, role } = await requireActiveCompany();
  const { q, page: pageParam } = await searchParams;

  const page = Math.max(1, Number(pageParam) || 1);
  const search = q?.trim();

  const where = {
    companyId: company.id,
    ...(search ? { bolNumber: { contains: search, mode: "insensitive" as const } } : {}),
  };

  const [records, total] = await Promise.all([
    prisma.bolRecord.findMany({
      where,
      orderBy: { generatedAt: "desc" },
      skip: (page - 1) * PAGE_SIZE,
      take: PAGE_SIZE,
      include: { generatedByUser: { select: { name: true } } },
    }),
    prisma.bolRecord.count({ where }),
  ]);

  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

  return (
    <div className="flex flex-col gap-6">
      <div>
        <h1 className="text-2xl font-semibold text-slate-900">BOL History</h1>
        <p className="mt-1 text-sm text-slate-500">{total} total records</p>
      </div>

      <form className="flex gap-2" action="/history">
        <input
          type="text"
          name="q"
          defaultValue={search}
          placeholder="Search by BOL number…"
          className="w-64 rounded-md border border-slate-300 px-3 py-2 text-sm"
        />
        <button
          type="submit"
          className="rounded-md border border-slate-300 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50"
        >
          Search
        </button>
      </form>

      <div className="overflow-hidden rounded-lg border border-slate-200 bg-white">
        <table className="w-full text-sm">
          <thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500">
            <tr>
              <th className="px-4 py-2">BOL No.</th>
              <th className="px-4 py-2">Date</th>
              <th className="px-4 py-2">Generated By</th>
              <th className="px-4 py-2">Status</th>
              <th className="px-4 py-2">PDF</th>
              {role === "ADMIN" ? <th className="px-4 py-2">Actions</th> : null}
            </tr>
          </thead>
          <tbody>
            {records.map((r) => (
              <tr key={r.id} className="border-t border-slate-100 align-top">
                <td className="px-4 py-2 font-medium text-slate-900">{r.bolNumber}</td>
                <td className="px-4 py-2 text-slate-500">{r.generatedAt.toLocaleString()}</td>
                <td className="px-4 py-2 text-slate-500">{r.generatedByUser.name}</td>
                <td className="px-4 py-2">
                  <span
                    className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                      r.status === "VOIDED"
                        ? "bg-red-100 text-red-700"
                        : "bg-emerald-100 text-emerald-700"
                    }`}
                  >
                    {r.status === "VOIDED" ? "Voided" : "Active"}
                  </span>
                  {r.status === "VOIDED" && r.voidReason ? (
                    <div className="mt-1 text-xs text-slate-400">{r.voidReason}</div>
                  ) : null}
                </td>
                <td className="px-4 py-2">
                  {r.pdfStatus === "READY" ? (
                    <a
                      href={`/api/companies/${company.id}/bols/${r.id}/pdf`}
                      target="_blank"
                      rel="noreferrer"
                      className="text-slate-700 underline"
                    >
                      Download
                    </a>
                  ) : (
                    <span className="text-xs text-slate-400">{r.pdfStatus}</span>
                  )}
                </td>
                {role === "ADMIN" ? (
                  <td className="px-4 py-2">
                    {r.status === "ACTIVE" ? (
                      <VoidButton companyId={company.id} bolId={r.id} />
                    ) : null}
                  </td>
                ) : null}
              </tr>
            ))}
            {records.length === 0 ? (
              <tr>
                <td colSpan={6} className="px-4 py-8 text-center text-sm text-slate-400">
                  No BOLs found.
                </td>
              </tr>
            ) : null}
          </tbody>
        </table>
      </div>

      {totalPages > 1 ? (
        <div className="flex items-center justify-center gap-3 text-sm text-slate-600">
          {page > 1 ? (
            <a
              href={`/history?${new URLSearchParams({ ...(search ? { q: search } : {}), page: String(page - 1) })}`}
              className="underline"
            >
              Previous
            </a>
          ) : null}
          <span>
            Page {page} of {totalPages}
          </span>
          {page < totalPages ? (
            <a
              href={`/history?${new URLSearchParams({ ...(search ? { q: search } : {}), page: String(page + 1) })}`}
              className="underline"
            >
              Next
            </a>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
